In [ ]:
!wget http://cs231n.stanford.edu/tiny-imagenet-200.zip
!unzip tiny-imagenet-200.zip


URL transformed to HTTPS due to an HSTS policy
--2025-06-02 02:55:50--  https://cs231n.stanford.edu/tiny-imagenet-200.zip
Resolving cs231n.stanford.edu (cs231n.stanford.edu)... 171.64.64.64
Connecting to cs231n.stanford.edu (cs231n.stanford.edu)|171.64.64.64|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 248100043 (237M) [application/zip]
Saving to: ‘tiny-imagenet-200.zip.1’

tiny-imagenet-200.z 100%[===================>] 236.61M  60.5MB/s    in 4.4s    

2025-06-02 02:55:55 (54.1 MB/s) - ‘tiny-imagenet-200.zip.1’ saved [248100043/248100043]

Archive:  tiny-imagenet-200.zip
replace tiny-imagenet-200/words.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: N


In [ ]:
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.Compose([
    transforms.Resize((64, 64)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5]*3, std=[0.5]*3)
])

train_dataset = datasets.ImageFolder('tiny-imagenet-200/train', transform=transform)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)

In [ ]:

!pip install torchattacks

!pip install git+https://github.com/Harry24k/adversarial-attacks-pytorch.git

!git clone https://github.com/Harry24k/adversarial-attacks-pytorch.git
!cd adversarial-attacks-pytorch/
!pip install -e .

  Cloning https://github.com/Harry24k/adversarial-attacks-pytorch.git to /tmp/pip-req-build-rq09xj2w
  Running command git clone --filter=blob:none --quiet https://github.com/Harry24k/adversarial-attacks-pytorch.git /tmp/pip-req-build-rq09xj2w
  Resolved https://github.com/Harry24k/adversarial-attacks-pytorch.git to commit 23620a694a3660e4f194c3e4d28992bced7785a1
  Preparing metadata (setup.py) ... done
fatal: destination path 'adversarial-attacks-pytorch' already exists and is not an empty directory.
Obtaining file:///content
ERROR: file:///content does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.


In [ ]:

!pip install torchattacks


import torch
import torchattacks
import timm
from torchvision import datasets, transforms
import matplotlib.pyplot as plt


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")


model = timm.create_model('vit_base_patch16_224', pretrained=True)
model = model.to(device)
model.eval()


print("Available attacks:")
attacks = [attr for attr in dir(torchattacks) if not attr.startswith('_')]
print(len(attacks), attacks)

images = torch.randn(4, 3, 224, 224).to(device)
labels = torch.randint(0, 1000, (4,)).to(device)


images = torch.clamp(images, 0, 1)


pgd = torchattacks.PGD(model, eps=8/255, alpha=2/255, steps=10)


adv_images = pgd(images, labels)

print("Original images shape:", images.shape)
print("Adversarial images shape:", adv_images.shape)
print("Attack completed successfully!")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.0/142.0 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 48.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 30.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 42.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 807.9 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

KeyboardInterrupt: 

In [ ]:
import timm

vit = timm.create_model('vit_base_patch16_224', pretrained=True)

print(f"Number of blocks: {len(vit.blocks)}")


first_block = vit.blocks[0]
middle_block = vit.blocks[6]
last_block = vit.blocks[11]

print(vit.blocks[0])


Number of blocks: 12
Block(
  (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
  (attn): Attention(
    (qkv): Linear(in_features=768, out_features=2304, bias=True)
    (q_norm): Identity()
    (k_norm): Identity()
    (attn_drop): Dropout(p=0.0, inplace=False)
    (proj): Linear(in_features=768, out_features=768, bias=True)
    (proj_drop): Dropout(p=0.0, inplace=False)
  )
  (ls1): Identity()
  (drop_path1): Identity()
  (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
  (mlp): Mlp(
    (fc1): Linear(in_features=768, out_features=3072, bias=True)
    (act): GELU(approximate='none')
    (drop1): Dropout(p=0.0, inplace=False)
    (norm): Identity()
    (fc2): Linear(in_features=3072, out_features=768, bias=True)
    (drop2): Dropout(p=0.0, inplace=False)
  )
  (ls2): Identity()
  (drop_path2): Identity()
)


In [ ]:

from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

inputs = processor(text=["a photo of a cat", "a photo of a dog"], images=image, return_tensors="pt", padding=True)

outputs = model(**inputs)
logits_per_image = outputs.logits_per_image
probs = logits_per_image.softmax(dim=1)

In [ ]:
#CLIP-vit-large-patch16
from PIL import Image
import requests
from transformers import CLIPProcessor, CLIPModel
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch16")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch16")
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
inputs = processor(text=["a photo of a cat", "a photo of a dog"], images=image, return_tensors="pt", padding=True)
outputs = model(**inputs)
logits_per_image = outputs.logits_per_image
probs = logits_per_image.softmax(dim=1)


###Image Processing

####test with small dataset

In [ ]:
import os
import shutil
from sklearn.model_selection import train_test_split
src_root = '/content/drive/MyDrive/cs231n_project/imagenet_val_subset'

train_root = '/content/drive/MyDrive/cs231n_project/imagenet_train_split'
val_root = '/content/drive/MyDrive/cs231n_project/imagenet_val_split'

train_ratio = 0.8

os.makedirs(train_root, exist_ok=True)
os.makedirs(val_root, exist_ok=True)

for class_name in os.listdir(src_root):
    class_dir = os.path.join(src_root, class_name)
    if not os.path.isdir(class_dir):
        continue

    image_files = os.listdir(class_dir)
    train_files, val_files = train_test_split(image_files, train_size=train_ratio, random_state=42)

    os.makedirs(os.path.join(train_root, class_name), exist_ok=True)
    os.makedirs(os.path.join(val_root, class_name), exist_ok=True)


    print(len(val_files))
    for f in val_files:
        shutil.copy(os.path.join(class_dir, f), os.path.join(val_root, class_name, f))


2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2


ValueError: With n_samples=1, test_size=None and train_size=0.8, the resulting train set will be empty. Adjust any of the aforementioned parameters.

In [ ]:
import os
import shutil

src_root = '/content/drive/MyDrive/cs231n_project/imagenet_val_subset'
val_root = '/content/drive/MyDrive/cs231n_project/imagenet_val_split'

os.makedirs(val_root, exist_ok=True)
i= 0
for class_name in os.listdir(src_root):
    class_dir = os.path.join(src_root, class_name)
    if not os.path.isdir(class_dir):
        continue

    image_files = sorted(os.listdir(class_dir))[:2]
    dest_dir = os.path.join(val_root, class_name)
    os.makedirs(dest_dir, exist_ok=True)


    for f in image_files:
      i+=1
      shutil.copy(os.path.join(class_dir, f), os.path.join(dest_dir, f))
      print(i)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


In [ ]:
print(len(os.listdir(src_root)))

NameError: name 'os' is not defined

In [ ]:
#CLIP-vit-large-patch14
#this is from huggingface
from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel

clip_model = CLIPModel.from_pretrained("openai/clip-vit-large-patch14")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-large-patch14")
# image = Image.open(requests.get(url, stream=True).raw)

# inputs = processor(text=["a photo of a cat", "a photo of a dog"], images=image, return_tensors="pt", padding=True)

# outputs = model(**inputs)
# logits_per_image = outputs.logits_per_image # this is the image-text similarity score
# probs = logits_per_image.softmax(dim=1) # we can take the softmax to get the label probabilities


model.safetensors:  18%|#8        | 388M/2.10G [00:00<?, ?B/s]

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.


preprocessor_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/905 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/961k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/525k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.22M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]

In [ ]:
i


                                            class_name   class_id   id
0                                   tench, Tinca tinca  n01440764    0
1                          goldfish, Carassius auratus  n01443537    1
2    great white shark, white shark, man-eater, man...  n01484850    2
3                      tiger shark, Galeocerdo cuvieri  n01491361    3
4                         hammerhead, hammerhead shark  n01494475    4
..                                                 ...        ...  ...
995                                          earthstar  n13044778  995
996  hen-of-the-woods, hen of the woods, Polyporus ...  n13052670  996
997                                             bolete  n13054560  997
998                              ear, spike, capitulum  n13133613  998
999       toilet tissue, toilet paper, bathroom tissue  n15075141  999

[1000 rows x 3 columns]
1000


NameError: name 'transform' is not defined

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
import torch
!pip install torchattacks
import torchattacks

import timm
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import pandas as pd
from tqdm import tqdm
import numpy as np

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5]*3, std=[0.5]*3)

])

import pandas as pd


csv_path = '/content/drive/MyDrive/cs231n_project/class_map.csv'
df = pd.read_csv(csv_path, quotechar='"')

print(df)

print(len(df["class_name"]))
name_to_index = dict(zip(df['class_name'], df['id']))

from torchvision import datasets


dataset = datasets.ImageFolder('/content/drive/MyDrive/cs231n_project/imagenet_val_split', transform=transform)

missing = [cls for cls in dataset.classes if cls not in name_to_index]
if missing:
    print("These class folders are not in the CSV:", missing)


dataset.class_to_idx = {cls: name_to_index[cls] for cls in dataset.classes}


test_loader = DataLoader(dataset, batch_size=32, shuffle=False)
# train_dataset = datasets.ImageFolder('tiny-imagenet-200/train', transform=transform)
# train_loader = DataLoader(train_dataset, batch_size=32, shuffle=False)  # Smaller batch for memory
print(test_loader)


print(len(test_loader))

import timm
import torch.nn as nn



                                            class_name   class_id   id
0                                   tench, Tinca tinca  n01440764    0
1                          goldfish, Carassius auratus  n01443537    1
2    great white shark, white shark, man-eater, man...  n01484850    2
3                      tiger shark, Galeocerdo cuvieri  n01491361    3
4                         hammerhead, hammerhead shark  n01494475    4
..                                                 ...        ...  ...
995                                          earthstar  n13044778  995
996  hen-of-the-woods, hen of the woods, Polyporus ...  n13052670  996
997                                             bolete  n13054560  997
998                              ear, spike, capitulum  n13133613  998
999       toilet tissue, toilet paper, bathroom tissue  n15075141  999

[1000 rows x 3 columns]
1000
35


In [ ]:
import timm
import torch.nn as nn


model = timm.create_model('vit_base_patch16_224', pretrained=True, num_classes=1000)

model = model.to(device)
model.eval()
class SimpleMLP(nn.Module):
    def __init__(self, feature_dim=768, num_classes=200):
        super(SimpleMLP, self).__init__()
        self.classifier = nn.Sequential(
            nn.Linear(feature_dim, 512),
            nn.ReLU(),
            nn.Linear(512, num_classes)
        )

    def forward(self, x):
        return self.classifier(x)


In [ ]:
feature_extractor = model
classifier = SimpleMLP().to(device)
optimizer = torch.optim.Adam(classifier.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()

for images, labels in train_loader:
    images, labels = images.to(device), labels.to(device)

    with torch.no_grad():
        features = feature_extractor(images)

    outputs = classifier(features)
    loss = criterion(outputs, labels)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()



NameError: name 'train_loader' is not defined

In [ ]:
print(device)

cuda


In [ ]:

attack_classes = []
for attr_name in dir(torchattacks):
    attr = getattr(torchattacks, attr_name)
    if (isinstance(attr, type) and
        hasattr(attr, '__call__') and
        attr_name not in ['Attack', 'MultiAttack']):
        attack_classes.append((attr_name, attr))

print(f"Found {len(attack_classes)} attacks:")
for name, _ in attack_classes:
    print(f"- {name}")

Found 38 attacks:
- APGD
- APGDT
- AutoAttack
- BIM
- CW
- DIFGSM
- DeepFool
- EADEN
- EADL1
- EOTPGD
- FAB
- FFGSM
- FGSM
- GN
- JSMA
- Jitter
- LGV
- MIFGSM
- NIFGSM
- OnePixel
- PGD
- PGDL2
- PGDRS
- PGDRSL2
- PIFGSM
- PIFGSMPP
- Pixle
- RFGSM
- SINIFGSM
- SPSA
- SparseFool
- Square
- TIFGSM
- TPGD
- UPGD
- VANILA
- VMIFGSM
- VNIFGSM


In [ ]:
def create_attack(attack_class, model, attack_name):
    try:
        if attack_name in ['PGD', 'FGSM', 'BIM', 'RFGSM', 'MIFGSM']:
            return attack_class(model, eps=8/255, alpha=2/255, steps=10)
        elif attack_name in ['CW']:
            return attack_class(model, c=1, lr=0.01, steps=50)
        elif attack_name in ['DeepFool']:
            return attack_class(model, steps=50)
        elif attack_name in ['AutoAttack']:
            return attack_class(model, norm='Linf', eps=8/255, version='standard')
        else:
            return attack_class(model)
    except Exception as e:
        print(f"Failed to create {attack_name}: {e}")
        return None

In [ ]:
print(len(test_loader))

35


In [ ]:
def evaluate_attack(model, processor, attack, test_loader, max_batches=10):
    """Evaluate model performance under attack."""
    correct_clean = 0
    correct_adv = 0
    total = 0




    model.eval()

    for batch_idx, (images, labels) in enumerate(test_loader):
        if batch_idx >= max_batches:
            break
        images, labels = images.to(device), labels.to(device)

        images_for_attack = images.clone().detach().requires_grad_(True)
        with torch.no_grad():

            inputs = processor(text=labels, images=images, return_tensors="pt", padding=True)
            outputs = model(**inputs)
            logits_per_image = outputs.logits_per_image
            outputs_clean = logits_per_image.softmax(dim=1)
            pred_clean = outputs_clean.argmax(dim=1)

            correct_clean += (pred_clean == labels).sum().item()
            print(correct_clean)
        try:
            adv_inputs = processor(text=labels, images=images, return_tensors="pt", padding=True)
            adv_outputs = model(**adv_inputs)
            adv_logits_per_image = adv_outputs.logits_per_image
            adv_outputs_clean = adv_logits_per_image.softmax(dim=1)
            pred_adv = adv_outputs_clean.argmax(dim=1)
            correct_adv += (pred_adv == labels).sum().item()
            print(correct_adv)
        except Exception as e:
            print(f"[Warning] Attack failed at batch {batch_idx}: {e}")
            correct_adv += (pred_clean == labels).sum().item()

        total += labels.size(0)

    clean_acc = correct_clean / total
    adv_acc = correct_adv / total
    attack_success_rate = 1 - adv_acc

    return clean_acc, adv_acc, attack_success_rate


In [ ]:

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")


if device.type == 'cuda':
    torch.backends.cudnn.benchmark = True
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")


def check_gpu_usage():
    if torch.cuda.is_available():
        print(f"GPU Memory Used: {torch.cuda.memory_allocated() / 1e9:.2f} GB")
        print(f"GPU Memory Cached: {torch.cuda.memory_reserved() / 1e9:.2f} GB")

Using device: cuda
GPU: Tesla T4
GPU Memory: 15.8 GB


In [ ]:
def clear_gpu_cache():
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


In [ ]:
class CombinedModel(nn.Module):
    def __init__(self, feature_extractor, classifier):
        super().__init__()
        self.feature_extractor = feature_extractor
        self.classifier = classifier

    def forward(self, x):

        features = self.feature_extractor(x)
        return self.classifier(features)


In [ ]:
results = []

for attack_name, attack_class in tqdm(attack_classes, desc="Testing attacks"):
    clear_gpu_cache()
    print(f"\nTesting {attack_name}...")

    attack = create_attack(attack_class, model, attack_name)
    if attack is None:
        continue

    try:
        clean_acc, adv_acc, success_rate = evaluate_attack(clip_model, processor, attack, test_loader)

        results.append({
            'Attack': attack_name,
            'Clean_Accuracy': clean_acc,
            'Adversarial_Accuracy': adv_acc,
            'Attack_Success_Rate': success_rate,
            'Performance_Drop': clean_acc - adv_acc
        })

        print(f"{attack_name}: Clean={clean_acc:.3f}, Adv={adv_acc:.3f}, Success={success_rate:.3f}")

    except Exception as e:
        print(f"Error with {attack_name}: {e}")
        continue
results_df = pd.DataFrame(results)

Testing attacks:   0%|          | 0/38 [00:00<?, ?it/s]


Testing APGD...


Testing attacks:   3%|▎         | 1/38 [00:00<00:10,  3.70it/s]

Error with APGD: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing APGDT...


Testing attacks:   5%|▌         | 2/38 [00:00<00:09,  3.85it/s]

Error with APGDT: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing AutoAttack...


Testing attacks:   8%|▊         | 3/38 [00:00<00:09,  3.80it/s]

Error with AutoAttack: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing BIM...


Testing attacks:  11%|█         | 4/38 [00:01<00:09,  3.76it/s]

Error with BIM: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing CW...


Testing attacks:  13%|█▎        | 5/38 [00:01<00:08,  3.71it/s]

Error with CW: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing DIFGSM...


Testing attacks:  16%|█▌        | 6/38 [00:01<00:08,  3.78it/s]

Error with DIFGSM: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing DeepFool...


Testing attacks:  18%|█▊        | 7/38 [00:01<00:08,  3.76it/s]

Error with DeepFool: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing EADEN...


Testing attacks:  21%|██        | 8/38 [00:02<00:07,  3.79it/s]

Error with EADEN: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing EADL1...


Testing attacks:  24%|██▎       | 9/38 [00:02<00:07,  3.77it/s]

Error with EADL1: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing EOTPGD...


Testing attacks:  26%|██▋       | 10/38 [00:02<00:07,  3.82it/s]

Error with EOTPGD: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing FAB...


Testing attacks:  29%|██▉       | 11/38 [00:02<00:07,  3.79it/s]

Error with FAB: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing FFGSM...


Testing attacks:  32%|███▏      | 12/38 [00:03<00:06,  3.81it/s]

Error with FFGSM: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing FGSM...
Failed to create FGSM: FGSM.__init__() got an unexpected keyword argument 'alpha'

Testing GN...


Testing attacks:  37%|███▋      | 14/38 [00:03<00:04,  4.93it/s]

Error with GN: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing JSMA...


Testing attacks:  39%|███▉      | 15/38 [00:03<00:04,  4.63it/s]

Error with JSMA: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing Jitter...


Testing attacks:  42%|████▏     | 16/38 [00:03<00:05,  4.35it/s]

Error with Jitter: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing LGV...
Failed to create LGV: LGV.__init__() missing 1 required positional argument: 'trainloader'

Testing MIFGSM...


Testing attacks:  47%|████▋     | 18/38 [00:04<00:03,  5.33it/s]

Error with MIFGSM: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing NIFGSM...


Testing attacks:  50%|█████     | 19/38 [00:04<00:03,  4.84it/s]

Error with NIFGSM: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing OnePixel...


Testing attacks:  53%|█████▎    | 20/38 [00:04<00:03,  4.57it/s]

Error with OnePixel: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing PGD...


Testing attacks:  55%|█████▌    | 21/38 [00:05<00:03,  4.32it/s]

Error with PGD: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing PGDL2...


Testing attacks:  58%|█████▊    | 22/38 [00:05<00:03,  4.16it/s]

Error with PGDL2: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing PGDRS...


Testing attacks:  61%|██████    | 23/38 [00:05<00:03,  4.07it/s]

Error with PGDRS: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing PGDRSL2...


Testing attacks:  63%|██████▎   | 24/38 [00:05<00:03,  3.95it/s]

Error with PGDRSL2: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing PIFGSM...


Testing attacks:  66%|██████▌   | 25/38 [00:06<00:03,  3.88it/s]

Error with PIFGSM: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing PIFGSMPP...


Testing attacks:  68%|██████▊   | 26/38 [00:06<00:03,  3.81it/s]

Error with PIFGSMPP: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing Pixle...


Testing attacks:  71%|███████   | 27/38 [00:06<00:02,  3.82it/s]

Error with Pixle: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing RFGSM...


Testing attacks:  74%|███████▎  | 28/38 [00:06<00:02,  3.74it/s]

Error with RFGSM: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing SINIFGSM...


Testing attacks:  76%|███████▋  | 29/38 [00:07<00:02,  3.74it/s]

Error with SINIFGSM: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing SPSA...


Testing attacks:  79%|███████▉  | 30/38 [00:07<00:02,  3.72it/s]

Error with SPSA: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing SparseFool...


Testing attacks:  82%|████████▏ | 31/38 [00:07<00:01,  3.70it/s]

Error with SparseFool: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing Square...


Testing attacks:  84%|████████▍ | 32/38 [00:08<00:01,  3.41it/s]

Error with Square: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing TIFGSM...


Testing attacks:  87%|████████▋ | 33/38 [00:08<00:01,  3.20it/s]

Error with TIFGSM: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing TPGD...


Testing attacks:  89%|████████▉ | 34/38 [00:08<00:01,  3.05it/s]

Error with TPGD: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Testing UPGD...


Testing attacks:  89%|████████▉ | 34/38 [00:09<00:01,  3.74it/s]


KeyboardInterrupt: 

In [ ]:
!pip install torchattacks

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.0/142.0 kB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 91.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 90.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 50.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 44.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 19.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

####Vit 16

In [ ]:
import torch
import torch.nn as nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, Dataset
import timm
import torchattacks
import pandas as pd
from tqdm import tqdm

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform

model = timm.create_model('vit_base_patch16_224', pretrained=True)
model = model.to(device)
model.eval()


config = resolve_data_config({}, model=model)
transform = create_transform(**config)

class RemappedImageFolder(datasets.ImageFolder):
    def __init__(self, root, transform, class_name_to_imagenet_idx):
        super().__init__(root, transform)


        self.imagenet_mapping = {}
        for folder_name, auto_idx in self.class_to_idx.items():
            if folder_name in class_name_to_imagenet_idx:
                imagenet_idx = class_name_to_imagenet_idx[folder_name]
                self.imagenet_mapping[auto_idx] = imagenet_idx
            else:
                print(f"Warning: {folder_name} not found in CSV mapping")

        print(f"Remapping {len(self.imagenet_mapping)} classes")
        print(f"Example mappings: {dict(list(self.imagenet_mapping.items())[:5])}")

    def __getitem__(self, index):
        image, auto_label = super().__getitem__(index)

        imagenet_label = self.imagenet_mapping.get(auto_label, auto_label)
        return image, imagenet_label
df = pd.read_csv('/content/drive/MyDrive/my231n/cs231n_project/class_map.csv', quotechar='"')
class_name_to_imagenet_idx = dict(zip(df['class_name'], df['id']))

dataset = RemappedImageFolder(
    '/content/drive/MyDrive/imagenet_val_split',
    transform=transform,
    class_name_to_imagenet_idx=class_name_to_imagenet_idx
)

test_loader = DataLoader(dataset, batch_size=16, shuffle=False)
print(f"Total batches: {len(test_loader)}")


print("\n=== TESTING FIXED MAPPING ===")
correct_total = 0
total_samples = 0

for batch_idx, (images, labels) in enumerate(test_loader):
    if batch_idx >= 5:
        break

    images, labels = images.to(device), labels.to(device)

    with torch.no_grad():
        outputs = model(images)
        predictions = outputs.argmax(dim=1)
        correct = (predictions == labels).sum().item()
        correct_total += correct
        total_samples += len(labels)

    print(f"Batch {batch_idx}: Labels {labels}, Predictions {predictions}, Correct: {correct}/{len(labels)}")

accuracy = correct_total / total_samples
print(f"\nFixed mapping accuracy: {accuracy:.3f}")

if accuracy > 0.1:
    print("correct so far")
else:
    print("error")


def create_attack(attack_class, model, attack_name):
    # try:
    #     if attack_name in ['PGD', 'FGSM', 'BIM', 'RFGSM', 'MIFGSM']:
    #         return attack_class(model, eps=8/255, alpha=2/255, steps=10)
    #     elif attack_name == 'CW':
    #         return attack_class(model, c=1, lr=0.01, steps=50, kappa=0)
    #     elif attack_name == 'DeepFool':
    #         return attack_class(model, steps=50, overshoot=0.02)
    #     elif attack_name in ['APGD', 'APGDT']:
    #         return attack_class(model, eps=8/255, steps=100, loss='ce', rho=0.75)
    #     elif attack_name == 'FAB':
    #         return attack_class(model, eps=8/255, steps=100, n_classes=1000)
    #     elif attack_name == 'Square':
    #         return attack_class(model, eps=8/255, n_queries=1000)  # Reduced queries
    #     elif attack_name == 'AutoAttack':
    #         return attack_class(model, eps=8/255, n_classes=1000, version='standard')
    #     else:
    #         return attack_class(model)
    return attack_class(model)
    # except Exception as e:
    #     print(f"Failed to create {attack_name}: {e}")
    #     return None

def evaluate_clean(model, test_loader, max_batches=10):
    correct_clean = 0
    correct_adv = 0
    total = 0

    model.eval()

    for batch_idx, (images, labels) in enumerate(test_loader):
        if batch_idx >= max_batches:
            break

        images, labels = images.to(device), labels.to(device)

        with torch.no_grad():
            pred_clean = model(images).argmax(dim=1)
            correct_clean += (pred_clean == labels).sum().item()

        total += labels.size(0)


        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    clean_acc = correct_clean / total if total > 0 else 0

    return clean_acc


def evaluate_attack(model, attack, test_loader, max_batches=10):
    correct_clean = 0
    correct_adv = 0
    total = 0
    failed_attacks = 0
    model.eval()

    for batch_idx, (images, labels) in enumerate(test_loader):
        if batch_idx >= max_batches:
            break

        images, labels = images.to(device), labels.to(device)


        try:
            images_adv_input = images.clone().detach().requires_grad_(True)
            adv_images = attack(images_adv_input, labels)

            with torch.no_grad():
                pred_adv = model(adv_images).argmax(dim=1)
                correct_adv += (pred_adv == labels).sum().item()
                print(pred_adv)

        except Exception as e:
            print(f"Attack failed on batch {batch_idx}: {e}")
            failed_attacks += 1

        total += labels.size(0)


        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    adv_acc = correct_adv / total if total > 0 else 0
    attack_success_rate = 1 - adv_acc if adv_acc >= 0 else 0

    if failed_attacks > 0:
        print(f"Failed attacks: {failed_attacks}/{max_batches} batches")

    return adv_acc, attack_success_rate

sample_attacks = [
    ('FGSM', torchattacks.FGSM),
    ('PGD', torchattacks.PGD),
    ('BIM', torchattacks.BIM)
]

results = []
clean_acc = evaluate_clean(model, test_loader, max_batches=10)
for name, attack_class in sample_attacks:
    print(f"\n▶️ Testing {name}...")
    attack = create_attack(attack_class, model, name)
    if attack is None:
        continue

    try:
        adv_acc, success = evaluate_attack(model, attack, test_loader, max_batches=10)
        print(f"{name}: Clean Acc={clean_acc:.3f} | Adv Acc={adv_acc:.3f} | Success={success:.3f}")
        results.append({
            'Attack': name,
            'Clean_Accuracy': clean_acc,
            'Adversarial_Accuracy': adv_acc,
            'Attack_Success_Rate': success
        })
    except Exception as e:
        print(f"Error in {name}: {e}")

if results and all(r['Clean_Accuracy'] > 0.1 for r in results):

    excluded_attacks = {'Attack', 'MultiAttack', 'VANILA', 'GN', 'DeepFool'}
    attack_classes = []

    for name in dir(torchattacks):
        if name.startswith('_') or name in excluded_attacks:
            continue

        attr = getattr(torchattacks, name)
        if isinstance(attr, type) and hasattr(attr, '__call__'):
            try:
                if hasattr(attr, '__init__') and 'model' in attr.__init__.__code__.co_varnames:
                    attack_classes.append((name, attr))
            except:
                continue


    tested_names = {r['Attack'] for r in results}
    attack_classes = [(name, cls) for name, cls in attack_classes if name not in tested_names]
    clean_acc = evaluate_clean(model, test_loader, max_batches=10)
    for name, cls in tqdm(attack_classes, desc="Testing remaining attacks"):
        print(f"\nTesting {name}...")

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

        attack = create_attack(cls, model, name)
        if attack is None:
            continue

        try:
            adv_acc, success = evaluate_attack(model, attack, test_loader, max_batches=10)
            print(f"{name}: Clean Acc={clean_acc:.3f} | Adv Acc={adv_acc:.3f} | Success={success:.3f}")
            results.append({
                'Attack': name,
                'Clean_Accuracy': clean_acc,
                'Adversarial_Accuracy': adv_acc,
                'Attack_Success_Rate': success
            })
        except Exception as e:
            print(f" Error in {name}: {e}")


if results:
    df_results = pd.DataFrame(results)
    df_results.to_csv('/content/drive/MyDrive/my231n/attack_results_vit_fixed.csv', index=False)
    print(f"\nEvaluated {len(results)} attacks successfully and saved results.")

    successful_results = [r for r in results if r['Clean_Accuracy'] is not None and r['Clean_Accuracy'] > 0]
    if successful_results:
        avg_clean = sum(r['Clean_Accuracy'] for r in successful_results) / len(successful_results)
        avg_adv = sum(r['Adversarial_Accuracy'] for r in successful_results) / len(successful_results)
        print(f"Average Clean Accuracy: {avg_clean:.3f}")
        print(f"Average Adversarial Accuracy: {avg_adv:.3f}")
else:
    print(" No successful results to save.")

Using device: cuda
Remapping 302 classes
Example mappings: {0: 160, 1: 47, 2: 49, 3: 386, 4: 87}
Total batches: 69

=== TESTING FIXED MAPPING ===
Batch 0: Labels tensor([160, 160, 160, 160,  47,  47,  47,  47,  49,  49,  49,  49, 386, 386,
        386, 386], device='cuda:0'), Predictions tensor([160, 160, 160, 160,  47,  47,  47,  47,  49,  35,  49,  49, 386, 386,
        386, 101], device='cuda:0'), Correct: 14/16
Batch 1: Labels tensor([ 87,  87,  87,  87, 275, 275, 275, 191, 191, 191, 191, 180, 180, 180,
        180,  50], device='cuda:0'), Predictions tensor([ 87,  87,  87,  87, 275, 275, 275, 191, 191, 191, 191, 180, 180, 179,
        180,  50], device='cuda:0'), Correct: 15/16
Batch 2: Labels tensor([ 50,  50,  50, 295, 295, 295, 295,  40,  40,  40, 137, 137, 137, 137,
        132, 132], device='cuda:0'), Predictions tensor([ 50,  50,  50, 294, 295, 295, 295,  40,  40,  46,  97, 137, 137, 137,
        132, 132], device='cuda:0'), Correct: 13/16
Batch 3: Labels tensor([132, 122, 1

Testing remaining attacks:   0%|          | 0/32 [00:00<?, ?it/s]


Testing APGD...
tensor([212, 676, 836, 852,  71,  39,  64,  46,  34,  35, 763, 103, 345, 356,
        223, 101], device='cuda:0')
tensor([502, 664, 381, 446, 507, 345, 217, 700, 265, 126, 190, 176, 570, 179,
        213,  32], device='cuda:0')
tensor([ 66,  41,  58, 294, 297, 232, 189,  46,  55,  46,  97,  97, 147,  97,
        129, 144], device='cuda:0')
tensor([ 18, 120, 316, 312, 519, 151, 607, 151, 552, 238, 238, 239, 363, 596,
        114, 356], device='cuda:0')
tensor([281, 457, 249, 259, 226, 187, 184, 669, 737, 816, 885, 267, 257, 204,
        212, 180], device='cuda:0')
tensor([232, 238, 237, 151, 218, 217, 209, 219, 227, 219, 761, 256, 791, 213,
        155, 151], device='cuda:0')
tensor([515, 240, 245, 151, 267, 241,  30, 193, 238, 163, 236, 160, 217, 827,
        879, 732], device='cuda:0')
tensor([754, 210, 217, 263, 219, 211, 262, 179, 253, 253, 157, 496, 712, 786,
        629, 679], device='cuda:0')
tensor([909, 756, 909, 469, 811,  23, 200, 234,  56, 234, 151, 120, 121

Testing remaining attacks:   3%|▎         | 1/32 [00:10<05:23, 10.43s/it]

tensor([936, 171, 871, 539, 709, 162, 219, 232, 162, 220,  51, 226, 192, 218,
        239, 167], device='cuda:0')
APGD: Clean Acc=0.869 | Adv Acc=0.000 | Success=1.000

Testing APGDT...
tensor([232, 259, 664, 836,  71,  39, 772,  46,  50,  35,   6, 103, 344, 578,
        346, 101], device='cuda:0')
tensor([945,   2, 367, 542, 276, 276, 274, 190, 181, 188, 188, 151, 151, 179,
        253,  44], device='cuda:0')
tensor([ 49,  49, 758, 294, 297, 214, 297,  46,  55,  46,  97,  98, 141,  99,
        134, 144], device='cuda:0')
tensor([134, 124,  79, 123, 120, 437, 377, 331, 330, 238, 238, 239, 293, 339,
          8, 373], device='cuda:0')
tensor([248, 269, 270, 259, 186, 187, 185,  71,  79, 563, 721, 703, 228, 815,
        188, 240], device='cuda:0')
tensor([210, 238, 238, 157, 218, 166, 155, 230, 227, 231, 250, 213, 879, 169,
        196, 265], device='cuda:0')
tensor([330, 551, 245, 201, 267, 256, 462, 246, 237, 727, 208, 212, 218, 754,
        745, 811], device='cuda:0')
tensor([754, 249

Testing remaining attacks:   6%|▋         | 2/32 [00:21<05:27, 10.91s/it]

tensor([936, 638, 836, 539, 282, 162, 162, 156, 162, 205, 205,  87, 251, 218,
        156, 156], device='cuda:0')
APGDT: Clean Acc=0.869 | Adv Acc=0.000 | Success=1.000

Testing AutoAttack...
tensor([212, 676, 213, 166, 737, 640,  64,  46, 494,  35, 763, 103, 345, 570,
        262, 101], device='cuda:0')
tensor([ 30, 769, 693, 792, 104, 690,  18, 185, 265, 184, 190, 159, 570, 179,
        213,  30], device='cuda:0')
tensor([ 66,  41,  58, 294, 297, 196, 189,  46,  55,  46,  97,  97, 206,  97,
        129, 144], device='cuda:0')
tensor([294, 120, 988, 312, 519, 151, 415, 151, 619, 238, 238, 239, 298, 596,
        491, 359], device='cuda:0')
tensor([363, 338, 249, 259, 226, 187, 184, 456, 626,  53, 721, 267, 175, 395,
        212, 166], device='cuda:0')
tensor([232, 164, 238, 151, 218, 166, 210, 219, 227, 219, 761, 256, 399, 169,
        155, 151], device='cuda:0')
tensor([981, 240, 245, 151, 267, 381, 254, 193, 238, 163, 236, 160, 161, 827,
        461, 732], device='cuda:0')
tensor([75

Testing remaining attacks:   9%|▉         | 3/32 [00:32<05:14, 10.86s/it]

tensor([936, 171, 292, 539, 721, 162, 219, 215, 162, 220,  51, 226, 252, 218,
        239, 218], device='cuda:0')
AutoAttack: Clean Acc=0.869 | Adv Acc=0.000 | Success=1.000

Testing CW...
tensor([176, 219, 163, 176,  46,  39,  46,  46,  50, 337,  50,  50, 101, 385,
        101, 101], device='cuda:0')
tensor([937, 534, 379, 792, 276, 274, 276, 183, 181, 184, 189, 159, 179, 179,
        242,  30], device='cuda:0')
tensor([ 49,  49,  49, 294, 297, 297, 297,  46,  46,  46,  97, 549,  98,  97,
        134, 134], device='cuda:0')
tensor([134, 124, 123, 124, 124, 330, 331, 338,   8, 238, 238, 239, 291, 355,
        150, 270], device='cuda:0')
tensor([277, 278, 249, 154, 185, 187, 186, 785, 845,  53, 721, 267, 175, 266,
        188, 240], device='cuda:0')
tensor([232, 240, 240, 157, 219, 218, 218, 231, 264, 231, 761, 184, 205, 184,
        155, 245], device='cuda:0')
tensor([242, 240, 245, 226, 197, 179, 254, 185, 238, 218, 210, 212, 217, 754,
        598, 632], device='cuda:0')
tensor([632, 

Testing remaining attacks:  12%|█▎        | 4/32 [01:15<11:03, 23.70s/it]

tensor([926, 774, 282, 904, 721, 162, 162, 215, 162, 220, 214, 239, 171, 218,
        239, 218], device='cuda:0')
CW: Clean Acc=0.869 | Adv Acc=0.000 | Success=1.000

Testing DIFGSM...
tensor([212, 185, 797, 176,  71,  39,  64,  46,  35, 125, 396, 103, 345, 385,
        101, 101], device='cuda:0')
tensor([907, 534, 805, 693, 276, 275, 275, 185, 265, 184, 190, 159, 811, 256,
        239,  30], device='cuda:0')
tensor([ 66,  49, 971, 294, 297, 196, 189,  46,  55, 941,  97, 805,  98, 137,
        129, 144], device='cuda:0')
tensor([190, 125, 124, 124, 519, 674, 126, 155, 296, 238, 238, 217, 298, 731,
        212, 105], device='cuda:0')
tensor([277, 643, 249, 154, 185, 157, 192, 785, 434,  53, 111, 267, 175, 204,
        202, 238], device='cuda:0')
tensor([232, 238, 238, 151, 218, 218, 210, 219, 270, 239, 761, 256, 256, 184,
        154, 151], device='cuda:0')
tensor([245, 239, 245, 205, 208, 381, 462, 193, 238, 168, 236, 212, 161, 827,
        598, 632], device='cuda:0')
tensor([884, 180,

Testing remaining attacks:  16%|█▌        | 5/32 [01:25<08:23, 18.66s/it]

tensor([926, 171, 292, 904, 721, 162, 219, 215, 156, 220, 212, 226, 171, 218,
        239, 218], device='cuda:0')
DIFGSM: Clean Acc=0.869 | Adv Acc=0.025 | Success=0.975

Testing EADEN...
tensor([169, 226, 797, 176, 462, 808,  46,  46,  50,  35, 815, 395, 101, 101,
        101, 101], device='cuda:0')
tensor([658, 338, 748, 542,  76, 293, 232, 267, 181, 163, 189, 242, 785, 179,
        189,  30], device='cuda:0')
tensor([397,  49,  49, 294, 334, 224, 297,  46,  46,  46,  97, 646,  98,  97,
         70, 131], device='cuda:0')
tensor([134, 858, 123, 124, 519, 330, 283, 283, 331, 238, 238, 239, 286, 671,
        355, 284], device='cuda:0')
tensor([270, 676, 249, 259, 201, 187, 260, 652, 855, 677, 721, 266, 175, 266,
        188, 240], device='cuda:0')
tensor([232, 240, 256, 215, 152, 218, 971, 229, 227, 157, 761, 184,  39, 151,
        151, 151], device='cuda:0')
tensor([158, 232, 391, 256, 267, 340, 283, 193, 254, 750, 157, 212, 217, 754,
        848, 481], device='cuda:0')
tensor([754, 2

Testing remaining attacks:  19%|█▉        | 6/32 [04:28<32:21, 74.66s/it]

tensor([936, 655, 251, 539, 857, 162, 215, 215, 162, 276, 205, 214, 198, 218,
        230, 212], device='cuda:0')
EADEN: Clean Acc=0.869 | Adv Acc=0.000 | Success=1.000

Testing EADL1...
tensor([169, 226, 797, 176, 462, 808,  55,  39,  50,  35, 815, 395, 101, 101,
        101, 101], device='cuda:0')
tensor([658, 338, 748, 542, 276, 293, 217, 267, 181, 163, 189, 242, 785, 179,
        189,  30], device='cuda:0')
tensor([397,  49,  49, 294, 334, 224, 297,  46,  46,  46,  97, 646,  97,  97,
        111, 134], device='cuda:0')
tensor([134, 858, 123, 124, 519, 330, 283, 283, 331, 238, 238, 239, 286, 671,
        355, 277], device='cuda:0')
tensor([270, 904, 249, 259, 201, 187, 260, 838, 855, 677, 885, 266, 175, 267,
        188, 240], device='cuda:0')
tensor([232, 240, 256, 215, 152, 218, 971, 229, 227, 157, 761, 184,  39, 151,
        151, 151], device='cuda:0')
tensor([158, 232, 391, 256, 267, 340, 182, 193, 182, 750, 157, 212, 217, 754,
        848,  36], device='cuda:0')
tensor([754, 23

Testing remaining attacks:  22%|██▏       | 7/32 [07:32<45:54, 110.18s/it]

tensor([936, 655, 282, 539, 282, 162, 162, 215, 162, 289, 205, 214, 164, 218,
        230, 212], device='cuda:0')
EADL1: Clean Acc=0.869 | Adv Acc=0.000 | Success=1.000

Testing EOTPGD...
tensor([232, 185, 168, 852, 737, 599,  64,  46, 879, 223, 397, 103, 345, 429,
        240, 178], device='cuda:0')
tensor([ 17, 769, 207, 792, 363, 603, 217, 691, 265, 999, 190, 176, 254, 256,
        213,  32], device='cuda:0')
tensor([ 66,  41, 143, 294, 297, 196, 189,  46,  55, 941,  97,  97,  92,  97,
        129, 144], device='cuda:0')
tensor([813, 120, 124, 312, 492, 151, 509, 151, 572, 238, 238, 217, 298, 731,
        427, 151], device='cuda:0')
tensor([186, 151, 249, 676, 185, 898, 192, 749, 626,  53, 885, 267, 175, 153,
        212, 166], device='cuda:0')
tensor([232, 164, 238, 151, 218, 210, 161, 219, 273, 239, 284, 193, 256, 184,
        155, 151], device='cuda:0')
tensor([981, 240, 245, 151, 208,  21, 183, 193, 238, 567, 236, 160, 161, 827,
        598, 732], device='cuda:0')
tensor([807, 1

Testing remaining attacks:  25%|██▌       | 8/32 [07:49<32:14, 80.60s/it] 

tensor([925, 171, 292, 904, 721, 219, 219, 215, 156, 786, 212, 192, 171, 218,
        237, 218], device='cuda:0')
EOTPGD: Clean Acc=0.869 | Adv Acc=0.006 | Success=0.994

Testing FAB...


Testing remaining attacks:  25%|██▌       | 8/32 [15:15<45:47, 114.47s/it]


KeyboardInterrupt: 

In [ ]:
from torchvision.datasets import ImageFolder
from torchvision.datasets.folder import default_loader, IMG_EXTENSIONS
import os

class SafeImageFolder(ImageFolder):
    def __init__(self, root, transform=None, target_transform=None, loader=default_loader, is_valid_file=None):

        classes, class_to_idx = self.find_classes_safe(root)
        samples = self.make_dataset_safe(root, class_to_idx, IMG_EXTENSIONS, is_valid_file)
        if len(samples) == 0:
            raise RuntimeError(f"Found 0 valid image files in {root}.")

        self.loader = loader
        self.extensions = IMG_EXTENSIONS
        self.root = root
        self.transform = transform
        self.target_transform = target_transform
        self.classes = classes
        self.class_to_idx = class_to_idx
        self.samples = samples
        self.targets = [s[1] for s in samples]

    def __getitem__(self, index):
        path, target = self.samples[index]
        sample = self.loader(path)
        if self.transform is not None:
            sample = self.transform(sample)
        if self.target_transform is not None:
            target = self.target_transform(target)
        return sample, target, path

    def find_classes_safe(self, dir):
        """Find only class folders that are non-empty"""
        classes = []
        class_to_idx = {}
        for entry in sorted(os.listdir(dir)):
            path = os.path.join(dir, entry)
            if os.path.isdir(path):
                valid = False
                for fname in os.listdir(path):
                    if fname.lower().endswith(tuple(e.lower() for e in IMG_EXTENSIONS)):
                        valid = True
                        break
                if valid:
                    classes.append(entry)
        class_to_idx = {cls_name: i for i, cls_name in enumerate(classes)}
        return classes, class_to_idx

    def make_dataset_safe(self, directory, class_to_idx, extensions, is_valid_file):
        """Build the dataset, skipping folders with no valid images"""
        instances = []
        for target_class in sorted(class_to_idx.keys()):
            class_index = class_to_idx[target_class]
            target_dir = os.path.join(directory, target_class)
            if not os.path.isdir(target_dir):
                continue
            for root, _, fnames in sorted(os.walk(target_dir)):
                for fname in sorted(fnames):
                    path = os.path.join(root, fname)
                    if fname.lower().endswith(tuple(ext.lower() for ext in extensions)):
                        item = path, class_index
                        instances.append(item)
        return instances


### Dataset Creation

In [ ]:
import torch
import torch.nn as nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, Dataset
import timm
import torchattacks
import pandas as pd
from tqdm import tqdm

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform

model = timm.create_model('vit_base_patch16_224', pretrained=True)
model = model.to(device)
model.eval()


config = resolve_data_config({}, model=model)
transform = create_transform(**config)

import os
import pandas as pd

root = '/content/drive/MyDrive/my231n/imagenet_val_split'
df = pd.read_csv('/content/drive/MyDrive/my231n/cs231n_project/class_map.csv')


existing_classes = [d for d in os.listdir(root) if os.path.isdir(os.path.join(root, d))]
df_filtered = df[df['class_name'].isin(existing_classes)]

df_filtered.to_csv('/content/drive/MyDrive/my231n/class_map_filtered.csv', index=False)

class_name_to_imagenet_idx = dict(zip(df_filtered['class_name'], df_filtered['id']))

dataset = SafeImageFolder(
    root='/content/drive/MyDrive/my231n/imagenet_val_split',
    transform=transform
)


test_loader = DataLoader(dataset, batch_size=16, shuffle=False)
print(f"Total batches: {len(test_loader)}")

def create_attack(attack_class, model, attack_name):
  return attack_class(model)


def save_adversarial_images(images, labels, paths, attack_name, output_root, metadata):
    attack_dir = os.path.join(output_root, attack_name)
    os.makedirs(attack_dir, exist_ok=True)

    for img_tensor, label, img_path in zip(images, labels, paths):
        class_name = os.path.basename(os.path.dirname(img_path))
        filename = os.path.basename(img_path)
        save_path = os.path.join(attack_dir, f"{class_name}_{filename}")

        img = TF.to_pil_image(img_tensor.cpu().clamp(0, 1))
        img.save(save_path)

        metadata.append({
            'image_path': save_path,
            'original_class': class_name,
            'attack_type': attack_name
        })

def generate_adversarial_dataset(model, attack_class, attack_name, loader, output_root):
    attack = create_attack(attack_class, model, attack_name)
    metadata = []

    for batch in tqdm(loader, desc=f"Generating {attack_name}"):
        try:
            images, labels, paths = batch
        except Exception as e:
            print(f"Skipping batch due to unpack error: {e}")
            continue

        for i in range(len(images)):
            try:
                image = images[i].unsqueeze(0).to(device)
                label = labels[i].unsqueeze(0).to(device)
                path = paths[i]

                image_input = image.clone().detach().requires_grad_(True)
                adv_image = attack(image_input, label)


                save_adversarial_images(
                    adv_image,
                    label,
                    [path],
                    attack_name,
                    output_root,
                    metadata
                )

            except Exception as e:
                print(f" Skipping image {paths[i]} due to error: {e}")
                continue

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    return metadata


output_root = '/content/drive/MyDrive/my231n/adversarial_val_dataset'
all_metadata = []

attacks = [
    ('FGSM', torchattacks.FGSM),
    ('PGD', torchattacks.PGD),
    ('BIM', torchattacks.BIM),
    ('CW', torchattacks.CW),
    ('EOTPGD', torchattacks.EOTPGD),
    ('APGD', torchattacks.APGD),
    ('APGDT', torchattacks.APGDT),
    ('FAB', torchattacks.FAB),
]

for name, cls in attacks:
    meta = generate_adversarial_dataset(model, cls, name, test_loader, output_root)
    all_metadata.extend(meta)

df_meta = pd.DataFrame(all_metadata)
df_meta.to_csv(os.path.join(output_root, 'metadata.csv'), index=False)



Using device: cuda
Total batches: 69


Generating FGSM:  99%|█████████▊| 68/69 [00:37<00:00,  1.80it/s]


UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/content/drive/MyDrive/my231n/imagenet_val_split/colobus, colobus monkey/ILSVRC2012_val_00027834.JPEG'>

In [ ]:
import os

root = '/content/drive/MyDrive/imagenet_train_split'
for dirpath, dirnames, filenames in os.walk(root):
    print(f"{dirpath} -> {len(filenames)} files")
    break


/content/drive/MyDrive/imagenet_train_split -> 0 files


In [ ]:
import os
import torch
import timm
import torchattacks
import pandas as pd
from tqdm import tqdm
from PIL import Image
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform
import torchvision.transforms.functional as TF

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

model = timm.create_model('vit_base_patch16_224', pretrained=True)
model = model.to(device).eval()
config = resolve_data_config({}, model=model)
transform = create_transform(**config)

def safe_loader(path):
    try:
        with open(path, 'rb') as f:
            return Image.open(f).convert('RGB')
    except:
        return None

class SafeImageFolder(datasets.ImageFolder):
    def __init__(self, root, transform):
        super().__init__(root, transform=transform, loader=safe_loader)

    def __getitem__(self, index):
        path, target = self.samples[index]
        sample = self.loader(path)

        while sample is None:
            index = (index + 1) % len(self.samples)
            path, target = self.samples[index]
            sample = self.loader(path)

        if self.transform is not None:
            sample = self.transform(sample)
        return sample, target, path

dataset = SafeImageFolder('/content/drive/MyDrive/my231n/imagenet_val_split', transform=transform)
test_loader = DataLoader(dataset, batch_size=16, shuffle=False)
print(f"Total batches: {len(test_loader)}")

def save_adversarial_images(images, labels, paths, attack_name, output_root, metadata):
    attack_dir = os.path.join(output_root, attack_name)
    os.makedirs(attack_dir, exist_ok=True)

    for img_tensor, label, img_path in zip(images, labels, paths):
        class_name = os.path.basename(os.path.dirname(img_path))
        filename = os.path.basename(img_path)
        save_path = os.path.join(attack_dir, f"{class_name}_{filename}")

        try:
            img = TF.to_pil_image(img_tensor.cpu().clamp(0, 1))
            img.save(save_path)

            metadata.append({
                'image_path': save_path,
                'original_class': class_name,
                'attack_type': attack_name
            })
        except Exception as e:
          print(f"Error saving image: {e}")
            continue

def generate_adversarial_dataset(model, attack_class, attack_name, loader, output_root):
    attack = attack_class(model)
    metadata = []

    for images, labels, paths in tqdm(loader, desc=f"Generating {attack_name}"):
        images, labels = images.to(device), labels.to(device)

        try:
            images_input = images.clone().detach().requires_grad_(True)
            adv_images = attack(images_input, labels)
            save_adversarial_images(adv_images, labels, paths, attack_name, output_root, metadata)
        except Exception as e:
            continue

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    return metadata

output_root = '/content/drive/MyDrive/my231n/adversarial_val_dataset'
all_metadata = []

attacks = [
    ('FGSM', torchattacks.FGSM),
    ('PGD', torchattacks.PGD),
    ('BIM', torchattacks.BIM),
    ('CW', torchattacks.CW),
    ('EOTPGD', torchattacks.EOTPGD),
    ('APGD', torchattacks.APGD),
    ('APGDT', torchattacks.APGDT),
    ('FAB', torchattacks.FAB),
    ('VANILA', torchattacks.VANILA),
    ('GN', torchattacks.GN),
    ('DeepFool', torchattacks.DeepFool),

]

for name, cls in attacks:
    meta = generate_adversarial_dataset(model, cls, name, test_loader, output_root)
    all_metadata.extend(meta)

df_meta = pd.DataFrame(all_metadata)
df_meta.to_csv(os.path.join(output_root, 'metadata.csv'), index=False)
print(f" Saved {len(all_metadata)} adversarial images.")


In [ ]:
df_meta = pd.DataFrame(all_metadata)
df_meta.to_csv(os.path.join(output_root, 'metadata.csv'), index=False)
print(f"Saved {len(all_metadata)} adversarial images.")

In [ ]:
import torchvision.transforms.functional as TF
from tqdm import tqdm
import os

def save_clean_images(loader, output_root, existing_meta=None):
    clean_dir = os.path.join(output_root, 'clean')
    os.makedirs(clean_dir, exist_ok=True)
    metadata = [] if existing_meta is None else existing_meta

    for images, labels, paths in tqdm(loader, desc="Saving clean images"):
        for img_tensor, label, img_path in zip(images, labels, paths):
            class_name = os.path.basename(os.path.dirname(img_path))
            filename = os.path.basename(img_path)
            save_path = os.path.join(clean_dir, f"{class_name}_{filename}")


            img = TF.to_pil_image(img_tensor.cpu().clamp(0, 1))
            img.save(save_path)


            metadata.append({
                'image_path': save_path,
                'original_class': class_name,
                'attack_type': 'clean'
            })

    return metadata


In [ ]:
from PIL import Image
import os

broken = []
root = '/content/drive/MyDrive/my231n/imagenet_val_split'
for dirpath, _, filenames in os.walk(root):
    for fname in filenames:
        fpath = os.path.join(dirpath, fname)
        try:
            with Image.open(fpath) as img:
                img.verify()
        except Exception:
            print(f"Corrupt: {fpath}")
            broken.append(fpath)

print(f"\nTotal broken images: {len(broken)}")


In [ ]:

output_root = '/content/drive/MyDrive/my231n/adversarial_val_dataset'
clean_meta = save_clean_images(test_loader, output_root)

df_clean = pd.DataFrame(clean_meta)
df_clean.to_csv(os.path.join(output_root, 'metadata_clean.csv'), index=False)

df_existing = pd.read_csv(os.path.join(output_root, 'metadata.csv'))
df_all = pd.concat([df_existing, df_clean], ignore_index=True)
df_all.to_csv(os.path.join(output_root, 'metadata_with_clean.csv'), index=False)

print(f"Saved {len(clean_meta)} clean images.")


In [ ]:
import pandas as pd
import torch
from torchvision import transforms
from torchvision.datasets.folder import default_loader
from tqdm import tqdm
import timm
from collections import defaultdict


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
vit = timm.create_model('vit_base_patch16_224', pretrained=True).eval().to(device)

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
])


metadata_path = "/content/drive/MyDrive/my231n/adversarial_val_dataset/metadata_with_clean.csv"
class_map_path = "/content/drive/MyDrive/my231n/cs231n_project/class_map.csv"

df = pd.read_csv(metadata_path)
class_map_df = pd.read_csv(class_map_path, header=None, names=["class_name", "wnid", "class_id"])

name_to_id = dict(zip(class_map_df["class_name"], class_map_df["class_id"]))

acc_by_attack = defaultdict(lambda: {"correct": 0, "total": 0})

for _, row in tqdm(df.iterrows(), total=len(df)):
    img_path = row["image_path"]
    label_name = row["original_class"]
    attack_type = row["attack_type"]

    if label_name not in name_to_id:
        print(f"Warning: '{label_name}' not found in class map, skipping.")
        continue

    gt_label = name_to_id[label_name]

    try:
        img = default_loader(img_path)
        img = transform(img).unsqueeze(0).to(device)

        with torch.no_grad():
            pred = vit(img).argmax(dim=1).item()

        acc_by_attack[attack_type]["total"] += 1
        acc_by_attack[attack_type]["correct"] += int(pred == gt_label)

    except Exception as e:
        print(f"Error on {img_path}: {e}")
        continue

for attack, stats in acc_by_attack.items():
    acc = stats["correct"] / stats["total"] if stats["total"] > 0 else 0.0
    print(f"{attack:10s}: {acc:.4f} ({stats['correct']} / {stats['total']})")


/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


model.safetensors:   0%|          | 0.00/346M [00:00<?, ?B/s]

100%|██████████| 13068/13068 [45:32<00:00,  4.78it/s]


=== Per-Attack Accuracy ===
FGSM      : 0.0000 (0 / 1089)
PGD       : 0.0000 (0 / 1089)
BIM       : 0.0000 (0 / 1089)
CW        : 0.0000 (0 / 1089)
EOTPGD    : 0.0000 (0 / 1089)
APGD      : 0.0000 (0 / 1089)
APGDT     : 0.0000 (0 / 1089)
FAB       : 0.0000 (0 / 1089)
VANILA    : 0.0000 (0 / 1089)
GN        : 0.0000 (0 / 1089)
DeepFool  : 0.0000 (0 / 1089)
clean     : 0.0000 (0 / 1089)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
